<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_KoltiTrade</name>
   <tag></tag>
   <elementGuidId>43bf06fa-fa78-4896-996d-e943c3b5d482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comp-keidh9zfmoreContainer1label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-keidh9zfmoreContainer1label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f40cff4c-4187-4a13-bb75-6551315f1d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1zyfI</value>
      <webElementGuid>4b103313-477f-4919-acf5-382509627fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-keidh9zfmoreContainer1label</value>
      <webElementGuid>64dda831-35a9-4955-8ef5-b90257e87006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KoltiTrade</value>
      <webElementGuid>47365880-2907-443e-867f-14a7760c2fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-keidh9zfmoreContainer1label&quot;)</value>
      <webElementGuid>a7ae959c-c195-4d10-bc8d-095475470fe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-keidh9zfmoreContainer1label']</value>
      <webElementGuid>d646baab-dcb4-49bc-9ed8-c12f286b990b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-keidh9zfmoreContainer1']/a/div/div/p</value>
      <webElementGuid>93693d99-53b2-4507-98d9-8fc1783e1675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiSkills'])[1]/following::p[7]</value>
      <webElementGuid>f6ae6c57-ed9e-427d-b3a6-fbbe5c365dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiPay'])[1]/following::p[7]</value>
      <webElementGuid>52f5f820-f455-4c5f-8b10-3885d7a158d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beyond Traceability'])[1]/preceding::p[3]</value>
      <webElementGuid>fdb3f41e-aaed-4c6c-a139-fcf72bdf3ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let’s make sustainable landscapes and seascapes the New Norm'])[1]/preceding::p[3]</value>
      <webElementGuid>fe476a4c-4899-42ce-9db9-8d726ff22da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a/div/div/p</value>
      <webElementGuid>64e8f6e9-3c03-4d54-88ba-0d0cfd2fc31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-keidh9zfmoreContainer1label' and (text() = 'KoltiTrade' or . = 'KoltiTrade')]</value>
      <webElementGuid>3289ea45-ad23-47f9-83f3-36527ca9cb01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
