<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Solutions</name>
   <tag></tag>
   <elementGuidId>220fd9d9-4e2f-4288-8b06-9b35fa1e698e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comp-keidh9zf2label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-keidh9zf2label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d2dbf737-e972-4418-88c7-9567f94ed4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1zyfI</value>
      <webElementGuid>d8d3799f-eaa9-445a-91fd-f225cf01114c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-keidh9zf2label</value>
      <webElementGuid>d6358107-5580-4ebb-a954-e99f7479dfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solutions</value>
      <webElementGuid>738259d2-c3c1-44b8-9286-b9cf2ede4b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-keidh9zf2label&quot;)</value>
      <webElementGuid>9f527e67-f985-4857-be1c-7414c916af0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-keidh9zf2label']</value>
      <webElementGuid>6f0c0d43-a36e-4278-bf81-628cf277c29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-keidh9zf2']/a/div/div/p</value>
      <webElementGuid>3d9ae227-a404-4116-b8ad-3fd894a8c7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::p[3]</value>
      <webElementGuid>c02c8431-c217-4fab-b9bf-ef50f6fbf896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiTrace'])[1]/preceding::p[1]</value>
      <webElementGuid>634a041c-34f2-4d43-827b-295a38295417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiTrade'])[1]/preceding::p[1]</value>
      <webElementGuid>7da26c0c-ff68-474b-a779-ceffc2215086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solutions']/parent::*</value>
      <webElementGuid>c1a7a42f-2122-4368-b0ec-9b1a28ff3602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/div/p</value>
      <webElementGuid>2f6a41c6-3f46-4d51-962c-ce57e5bb172a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-keidh9zf2label' and (text() = 'Solutions' or . = 'Solutions')]</value>
      <webElementGuid>d64a4881-d49f-42d6-86ec-4ede592df6ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
